### ISSUE TITLE
Rebot tests cannot be run in parallel

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#109]
The Rebot tests instantiate a dummy server, and all tests use the same port. Hence the tests cannot be run in parallel.

Use different ports. Best use random ports (check how it is done for doocs in the DOOC CS adapter and/or the DOOCS backend)

**Comment by mhier** [comment]
Even worse, the tests will fail if run in parallel. Somehow, on Jenkins tests were not run in parallel recently due to a bug in our scripts there. Now this bug has been fixed and the Rebot tests fail consistently. We now have to force all tests of DeviceAccess to run sequentially because of this bug.

**Comment by mhier** [comment]
Minimum solution would be to use a locking mechanism to prevent the tests from failing when running in parallel.

**Comment by mhier** [comment]
See #176
